reverted recent changes for finished status handling

diff --git a/hooks/slurm/status b/hooks/slurm/status
--- a/hooks/slurm/status
+++ b/hooks/slurm/status
@@ -5,16 +5,16 @@
 #return code 2 = failed
 #return code 3 = unknown (retry later)
 
-if [ -f finished ]; then
-    code=$(cat finished)
-    if [ $code == 0 ]; then
-        echo "finished successfully"
-        exit 1
-    else
-        echo "failed with code:$code"
-        exit 2
-    fi
-fi
+#if [ -f finished ]; then
+#    code=$(cat finished)
+#    if [ $code == 0 ]; then
+#        echo "finished successfully"
+#        exit 1
+#    else
+#        echo "failed with code:$code"
+#        exit 2
+#    fi
+#fi
 
 if [ ! -f jobid ];then
 	echo "no jobid - not yet submitted?"
