added hack to capture exit code from pbs.. by storing to file. I should check with karst admin to see how long they keep their jobs in the queue after completing

diff --git a/hooks/pbs/start b/hooks/pbs/start
--- a/hooks/pbs/start
+++ b/hooks/pbs/start
@@ -1,2 +1,13 @@
 #!/bin/bash
-qsub -d $PWD -V -o \$PBS_JOBID.log -e \$PBS_JOBID.err main > jobid
+
+#pbs doesn't keep finished job long enough for amaretti to query its exit code..
+#to be absolutely sure that I can catch the exit code, I need to create a script that wraps the main.
+#but, if we do that, we get rid of all #PBS options that user might be setting inside main..
+#so create a fake submit script by pulling all #.. and call the original main and capture exit-code
+grep --regexp="^#" main > _main
+echo "rm -f exit-code" >> _main
+echo "./main" >> _main
+echo "echo \$? > exit-code" >> _main
+chmod +x _main
+
+qsub -d $PWD -V -o \$PBS_JOBID.log -e \$PBS_JOBID.err _main > jobid
